- name: Install OpenVPN
  yum:
    name: "{{ item }}"
    state: present
  with_items:
    - openvpn
    - easy-rsa

- name: Create OpenVPN server config
  template:
    src: "{{ item }}.j2"
    dest: "/etc/openvpn/server/{{ item }}"
  with_items:
    - server.conf
  notify:
    - restart openvpn

- name: Create OpenVPN keys directory
  file:
    path: /etc/openvpn/easy-rsa/keys
    state: directory
    mode: 0755
    recurse: yes

- name: Copy files for key generation
  copy:
    src: /usr/share/easy-rsa/2.0/*
    dest: /etc/openvpn/keys
    remote_src: yes

- name: Copy SSL config
  copy:
    src: /etc/openvpn/easy-rsa/openssl-1.0.0.cnf
    dest: /etc/openvpn/easy-rsa/openssl.cnf
    remote_src: yes

- name: Configure Key generation settings
  template:
    src: "{{ item }}"
    dest: "/etc/openvpn/easy-rsa/{{ item }}"
  with_item:
    - vars

- name: Generate keys
  command: "source ./vars; ./clean-all; ./build-ca --batch; ./build-key-server --batch server; ./build-dh"
  args:
    chdir: "/etc/openvpn/easy-rsa"
    creates:

  when:

- name: Copy generated Keys to OpenVPN folder
  copy:
    src: "{{ item }}"
    dest: /etc/openvpn
    remote_src: yes
  with_items:
    - dh2048.pem
    - ca.crt
    - server.crt
    - server.key

- name: Configure OpenVPN autostart
  service:
    name: openvpn
    enabled: yes
    state: started

- name: Enable IP forwarding
  sysctl:
    name: net.ipv4.ip_forward
    value: 1
    ignoreerrors: yes
    sysctl_set: yes
    state: present
    reload: yes
  failed_when: false

- name: Configure NAT for VPN
  iptables:
    table: nat
    chain: POSTROUTING
    out_interface: eth0
    jump: MASQUERADE

- name: Save IPTABLES configuration
  command: "iptables-save > /etc/sysconfig/iptables"




