- name: Create NGINX SSL directory
  file:
    path: "{{ ssl_dir }}"
    state: directory
    owner: nginx
    group: nginx
    mode: 0700

- name: Create self-signed SSL certificate
  command: openssl req -new -x509 -days 3650 -nodes -subj "/C=US/ST=Massachusets/L=Boston/O=IT/CN={{ fqdn }}" -out cert.pem -keyout cert.key -extensions v3_ca
  args:
    chdir: "{{ ssl_dir }}"
    creates: "{{ ssl_dir }}/cert.pem"
  notify: reload nginx

- name: Install NGINX SSL configuration
  template:
    src: "{{ item }}.j2"
    dest: "{{ conf_dir }}/{{ item }}"
    mode: 0644
  with_items:
    - ssl.conf
  notify: reload nginx

- name: Create NGINX apps configuration directory
  file:
    path: "{{ apps_conf_dir }}"
    state: directory
    owner: nginx
    group: nginx
    mode: 0700
